---
"on":
  push:
    branches: [main]

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/am43-bleak
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          path: "."
          package-name: am43-bleam
          release-type: python
          token: "${{ secrets.PAT_GITHUB_PR }}"
          versioning-strategy: "always-bump-patch"
          monorepo-tags: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"chore","section":"Miscellaneous","hidden":false},
             {"type":"test","section":"Tests","hidden":true},
             {"type":"ci","section":"Continuous Integration","hidden":true},
             {"type":"docs","section":"Documentation","hidden":false},
             {"type":"refactor","section":"Code Refactoring","hidden":true},
             {"type":"style","section":"Styles","hidden":true}]

      - name: Print release-please outputs
        run: |
          cat <<END
          ${{toJSON(steps.release.outputs)}}
          END
        continue-on-error: true

      # The logic below handles the pypi publication:
      - name: Checkout sources
        uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.release.outputs.releases_created }}
